name: WebAssembly

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/webassembly.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # For uploading release assets
    runs-on: windows-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_PATH: ${{ github.event.repository.name }}\\build
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_wasm

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        path: ${{ env.PROJECT_NAME }}

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.64
        actions-cache-folder: 'emsdk-cache'

    - name: Setup Release Paths
      run: |
        echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_wasm" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Setup Environment
      run: |
        mkdir ${{ env.PROJECT_RELEASE_PATH }}
        dir
      shell: cmd

    - name: Build Product
      run: |
        cd ${{ env.PROJECT_NAME }}
        mkdir build && cd build
        emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Emscripten -G "Unix Makefiles"
        cmake --build . --config Release
      shell: bash

    - name: Generate Artifacts
      run: |
        dir ${{ env.PROJECT_BUILD_PATH }}\src
        copy /Y ${{ env.PROJECT_BUILD_PATH }}\src\*.wasm ${{ env.PROJECT_RELEASE_PATH }}\
        copy /Y ${{ env.PROJECT_BUILD_PATH }}\src\*.data ${{ env.PROJECT_RELEASE_PATH }}\
        copy /Y ${{ env.PROJECT_BUILD_PATH }}\src\*.js ${{ env.PROJECT_RELEASE_PATH }}\
        copy /Y ${{ env.PROJECT_BUILD_PATH }}\src\*.html ${{ env.PROJECT_RELEASE_PATH }}\index.html
        copy /Y ${{ env.PROJECT_NAME }}\README.md ${{ env.PROJECT_RELEASE_PATH }}\README.md
        copy /Y ${{ env.PROJECT_NAME }}\LICENSE ${{ env.PROJECT_RELEASE_PATH }}\LICENSE
        dir ${{ env.PROJECT_RELEASE_PATH }}
        7z a -tzip -r .\${{ env.PROJECT_RELEASE_PATH }}.zip .\${{ env.PROJECT_RELEASE_PATH }}\*
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
